name: 问题反馈 Bug report
description: 程序出现问题 | Report the error to help lalc improve.
labels: ['bug']
title: "[Bug] "
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 应该确定的 | Confirm
      options:
      - label: 我填写的标题意义明确，而不是"一个建议"、"卡住了","LALC无法运行"等 | My title is clear, not something like "A suggestion", "Stuck", "LALC can't run", etc.
        required: true
      - label:  我已确认目前没有类似 issue | I have confirmed that there is no similar issue at this time. 
        required: true
      - label: 我使用的程序版本已为最新版 | I am using the latest program version.
        required: true
  - type: textarea
    id: describe
    attributes:
      label: 问题描述 | Bug Description
      description: 请尽可能详细描述你的问题，越详细修复得很可能越快 | Please describe your problem as detailed as possible, the more detailed the description, the faster it might get fixed.
    validations:
      required: true
  - type: textarea
    id: rebug
    attributes:
      label: 重现问题 | Reproduce the Bug
      description: 在（什么时候），做（什么行为），LALC 出现（什么问题） | When (time), doing (what operation), LALC shows (what problem)
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: 日志文件 | Log Files (Debug Info Warning Error)
      description: 请在日志页导出最上面的一份日志提交 | Please export and submit the most recent log from the log page
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 录屏/截图 | Record Video/Screenshot
      description: 上传你发生此问题时的录屏/截图 | Upload the video/screenshot when encountering this bug
    validations:
      required: false
  - type: textarea
    id: shouldbe
    attributes:
      label: 应该是？ | Expected Effect
      description: 描述你认为应为的实际效果 | Describe what the correct behavior should be
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: 其他信息 | Other Information
      description: 操作系统、语言及 LALC 版本号；屏幕分辨率(100%, 125%, 150%... 注意 LALC 在 150% 最稳定)等。| OS, language, LALC version number; screen resolution (100%, 125%, 150%... Note that LALC is most stable at 150%), etc.
    validations:
      required: false