from __future__ import annotations

import ast
import json
import subprocess
import sys
import threading
import uuid
from copy import deepcopy
from pathlib import Path
from typing import Any, Callable

from .runtime import (
    ExampleRunContext,
    ExecutionAnomaly,
    RunGate,
    TaskCancelled,
    atomic_write_json,
    load_verified_module,
    sha256_bytes,
)

BASE_COMPONENT = "example.step.base"
CANDIDATE_ROLE = "step"
BASE_SOURCE = '''"""Shipped Example Step placeholder."""
from lalc import step

@step
def execute(ctx, *, amount=1):
    return {"completed": True, "amount": amount}
'''
CANDIDATE_SOURCE = '''"""Example replacement Step generated by the fake Agent Adapter."""
from lalc import api_version, step

@step
def execute(ctx, *, amount=1):
    if ctx.observe("candidate_should_fail"):
        raise RuntimeError("scripted candidate failure")
    if ctx.observe("candidate_should_hang"):
        import time
        time.sleep(3600)
    ctx.control("complete_example", amount)
    return {"completed": True, "amount": amount, "api_version": api_version()}
'''


class DemoService:
    """Shared application seam for the GUI and acceptance tests."""

    def __init__(
        self,
        data_root: Path,
        *,
        runner_timeout: float = 5.0,
        on_change: Callable[[dict[str, Any]], None] | None = None,
    ) -> None:
        self.data_root = Path(data_root)
        self.runner_timeout = runner_timeout
        self.on_change = on_change
        self.gate = RunGate()
        self._condition = threading.Condition()
        self._thread: threading.Thread | None = None
        self._runner: subprocess.Popen[str] | None = None
        self._runtime_decision: tuple[str, str] | None = None
        self._capability_decision: str | None = None
        self._latest_candidate: dict[str, Any] | None = None
        self._state: dict[str, Any] = {
            "phase": "idle",
            "paused": False,
            "active_manifest_id": "base",
            "working_manifest_id": "base",
            "remaining_turns": 0,
            "result": None,
            "trace": [],
            "pending_review": None,
            "pending_capability": None,
        }
        self._active_manifest = self._base_manifest("base")
        self._working_manifest = deepcopy(self._active_manifest)
        self._run_dir: Path | None = None
        self._ensure_layout()

    def _ensure_layout(self) -> None:
        for name in ("components", "manifests", "traces", "logs", "runs"):
            (self.data_root / name).mkdir(parents=True, exist_ok=True)
        base_source = BASE_SOURCE.encode()
        base_path = self.data_root / "components" / f"{BASE_COMPONENT}.py"
        if not base_path.exists():
            base_path.write_bytes(base_source)
        if sha256_bytes(base_path.read_bytes()) != sha256_bytes(base_source):
            raise ValueError("shipped_base_component_changed")
        active_path = self.data_root / "manifests" / "active.json"
        if active_path.exists():
            self._active_manifest = json.loads(active_path.read_text(encoding="utf-8"))
            self._working_manifest = deepcopy(self._active_manifest)
            self._state["active_manifest_id"] = self._active_manifest["manifest_id"]
            self._state["working_manifest_id"] = self._active_manifest["manifest_id"]
        else:
            atomic_write_json(active_path, self._active_manifest)

    @staticmethod
    def _base_manifest(manifest_id: str) -> dict[str, Any]:
        return {
            "manifest_id": manifest_id,
            "components": {
                "example.current_step": {
                    "component_id": BASE_COMPONENT,
                    "sha256": sha256_bytes(BASE_SOURCE.encode()),
                }
            },
            "trusted_actions": {"observe": "example.observe", "control": "example.control"},
        }

    def snapshot(self) -> dict[str, Any]:
        with self._condition:
            return deepcopy(self._state)

    def wait_for(self, predicate: Callable[[dict[str, Any]], bool], timeout: float = 5.0) -> dict[str, Any]:
        with self._condition:
            if not self._condition.wait_for(lambda: predicate(self._state), timeout):
                raise TimeoutError(f"state wait timed out: {self._state['phase']}")
            return deepcopy(self._state)

    def start(self, scenario: dict[str, Any] | None = None, *, max_turns: int = 2) -> None:
        with self._condition:
            if self._thread and self._thread.is_alive():
                raise RuntimeError("task_already_running")
            self.gate = RunGate()
            self._runtime_decision = None
            self._capability_decision = None
            self._latest_candidate = None
            self._working_manifest = deepcopy(self._active_manifest)
            self._state.update(
                phase="starting",
                paused=False,
                working_manifest_id=self._working_manifest["manifest_id"],
                remaining_turns=max_turns,
                result=None,
                trace=[],
                pending_review=None,
                pending_capability=None,
                last_feedback="",
            )
            self._run_dir = self.data_root / "runs" / uuid.uuid4().hex
            self._run_dir.mkdir(parents=True)
            self._thread = threading.Thread(
                target=self._run,
                args=(deepcopy(scenario or {"supported": False}), max_turns),
                name="lalc-demo-workflow",
                daemon=True,
            )
            self._thread.start()
            self._changed_locked()

    def pause(self) -> None:
        self.gate.pause()
        self._set_state(paused=True)

    def resume(self) -> None:
        self.gate.resume()
        self._set_state(paused=False)

    def stop(self) -> None:
        self.gate.stop()
        with self._condition:
            runner = self._runner
            self._condition.notify_all()
        if runner and runner.poll() is None:
            runner.terminate()

    def decide_runtime(self, decision: str, feedback: str = "") -> None:
        if decision not in {"approve", "reject", "terminate"}:
            raise ValueError("invalid_runtime_decision")
        if decision == "reject" and not feedback.strip():
            raise ValueError("feedback_required")
        with self._condition:
            if self._state["phase"] != "runtime_review":
                raise RuntimeError("runtime_review_not_pending")
            self._runtime_decision = (decision, feedback.strip())
            self._condition.notify_all()
        if decision == "terminate":
            self.stop()

    def decide_capability(self, decision: str) -> None:
        if decision not in {"approve", "reject"}:
            raise ValueError("invalid_capability_decision")
        with self._condition:
            if self._state["phase"] != "capability_review":
                raise RuntimeError("capability_review_not_pending")
            self._capability_decision = decision
            self._condition.notify_all()

    def _run(self, scenario: dict[str, Any], max_turns: int) -> None:
        candidate: dict[str, Any] | None = None
        trial_succeeded = False
        try:
            self._phase("running")
            self._trace("task_started", scenario=scenario)
            try:
                result = self._execute_current_step(scenario)
            except ExecutionAnomaly as anomaly:
                self._trace("execution_anomaly", message=str(anomaly))
                result, candidate, trial_succeeded = self._recover(scenario, max_turns)
            if not isinstance(result, dict) or result.get("completed") is not True:
                raise ExecutionAnomaly("task_verification_failed")
            task_result = {"status": "success", "value": result}
            self._trace("task_verified", result=result)
        except TaskCancelled:
            candidate = self._latest_candidate
            task_result = {"status": "failure", "failure_code": "user_cancelled"}
            self._trace("task_cancelled")
        except ExecutionAnomaly as error:
            task_result = {"status": "failure", "failure_code": str(error)}
            self._trace("task_failed", failure_code=str(error))
        except Exception as error:
            task_result = {"status": "failure", "failure_code": "task_exception", "failure_message": str(error)}
            self._trace("task_failed", failure_code="task_exception", failure_message=str(error))
        self._finish(task_result, candidate, trial_succeeded)

    def _recover(
        self, scenario: dict[str, Any], max_turns: int
    ) -> tuple[dict[str, Any], dict[str, Any] | None, bool]:
        candidate = None
        for turn in range(1, max_turns + 1):
            self.gate.wait()
            self._set_state(remaining_turns=max_turns - turn)
            candidate = self._agent_turn(turn, scenario)
            self._show_runtime_review(candidate)
            decision, feedback = self._wait_runtime_decision()
            self._trace("runtime_reviewed", decision=decision, feedback=feedback)
            if decision == "terminate":
                raise TaskCancelled
            if decision == "reject":
                continue

            previous = deepcopy(self._working_manifest)
            self._replace_working_manifest(candidate["manifest"])
            self._trace("working_manifest_selected", manifest_id=self._working_manifest["manifest_id"])
            self.gate.wait()
            trial_scenario = {**scenario, "candidate_should_fail": turn <= scenario.get("candidate_fail_turns", 0)}
            trial = self._trial(candidate, trial_scenario)
            if self.gate.stopped:
                raise TaskCancelled
            self._trace("candidate_trial", **trial)
            if trial["status"] == "success":
                for event in trial["action_events"]:
                    self._trace("trusted_action", **event)
                return trial["result"], candidate, True
            if turn < max_turns:
                self._replace_working_manifest(previous)
                self._trace("working_manifest_rolled_back", reason="trial_failed_before_next_turn")
        raise ExecutionAnomaly("agent_session_exhausted")

    def _execute_current_step(self, scenario: dict[str, Any]) -> dict[str, Any]:
        binding = self._working_manifest["components"]["example.current_step"]
        if binding["component_id"] != BASE_COMPONENT:
            path = Path(binding["source_path"])
            source = path.read_bytes()
            module = load_verified_module(path, source, binding["sha256"])
            context = ExampleRunContext(
                scenario,
                before_action=self.gate.wait,
                event_sink=lambda event: self._trace("trusted_action", **event),
            )
            try:
                return module.execute(context, amount=scenario.get("amount", 1))
            except TaskCancelled:
                raise
            except Exception as error:
                raise ExecutionAnomaly(str(error)) from error
        self.gate.wait()
        self._trace("trusted_action", action="observe", name="supported", result=scenario.get("supported"))
        if scenario.get("step_external_failure"):
            raise RuntimeError("step_external_failure")
        if not scenario.get("supported"):
            raise ExecutionAnomaly("example_step_unsupported_state")
        return {"completed": not scenario.get("verification_fails", False), "amount": scenario.get("amount", 1)}

    def _agent_turn(self, turn: int, scenario: dict[str, Any]) -> dict[str, Any]:
        source = CANDIDATE_SOURCE.encode()
        digest = sha256_bytes(source)
        component_id = f"example.step.candidate.{digest[:12]}"
        path = self.data_root / "components" / f"{component_id}.py"
        if not path.exists():
            path.write_bytes(source)
        self._validate_candidate(path, digest)
        manifest = deepcopy(self._working_manifest)
        manifest["manifest_id"] = f"working-{digest[:12]}"
        manifest["components"]["example.current_step"] = {
            "component_id": component_id,
            "sha256": digest,
            "source_path": str(path),
        }
        log = {
            "turn": turn,
            "snapshot": {"anomaly": "example_step_unsupported_state", "scenario": scenario},
            "feedback": self._state.get("last_feedback", ""),
            "response": {"type": "working_manifest_update", "component_id": component_id},
        }
        atomic_write_json(self.data_root / "logs" / f"{self._run_dir.name}-turn-{turn}.json", log)
        atomic_write_json(
            self._run_dir / "candidate-file-batch.json",
            {"files": [{"path": str(path), "component_id": component_id, "sha256": digest}]},
        )
        self._trace("agent_turn", turn=turn, component_id=component_id)
        candidate = {"source_path": str(path), "source": source.decode(), "sha256": digest, "manifest": manifest}
        self._latest_candidate = candidate
        return candidate

    def _validate_candidate(self, path: Path, digest: str) -> None:
        source = path.read_bytes()
        if sha256_bytes(source) != digest:
            raise ValueError("candidate_sha256_mismatch")
        tree = ast.parse(source, filename=str(path))
        functions = [node for node in tree.body if isinstance(node, ast.FunctionDef) and node.name == "execute"]
        signature = functions[0].args if len(functions) == 1 else None
        if (
            signature is None
            or [argument.arg for argument in signature.args] != ["ctx"]
            or [argument.arg for argument in signature.kwonlyargs] != ["amount"]
            or signature.vararg is not None
            or signature.kwarg is not None
        ):
            raise ValueError("candidate_signature_invalid")
        decorators = [node.id for node in functions[0].decorator_list if isinstance(node, ast.Name)]
        if decorators != [CANDIDATE_ROLE]:
            raise ValueError("candidate_role_invalid")
        allowed_imports = {"lalc", "time"}
        for node in ast.walk(tree):
            if isinstance(node, ast.Import) and any(alias.name not in allowed_imports for alias in node.names):
                raise ValueError("candidate_import_invalid")
            if isinstance(node, ast.ImportFrom) and node.module not in allowed_imports:
                raise ValueError("candidate_import_invalid")
            if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and isinstance(node.func.value, ast.Name):
                if node.func.value.id == "ctx" and node.func.attr not in {"observe", "control"}:
                    raise ValueError("candidate_trusted_action_invalid")

    def _trial(self, candidate: dict[str, Any], scenario: dict[str, Any]) -> dict[str, Any]:
        assert self._run_dir is not None
        trial_id = uuid.uuid4().hex
        request_path = self._run_dir / f"candidate-request-{trial_id}.json"
        result_path = self._run_dir / f"candidate-result-{trial_id}.json"
        request = {
            "protocol_version": 1,
            "source_path": candidate["source_path"],
            "expected_sha256": candidate["sha256"],
            "arguments": {"amount": scenario.get("amount", 1)},
            "example_scenario": scenario,
            "result_path": str(result_path),
        }
        atomic_write_json(request_path, request)
        command = [sys.executable]
        if not getattr(sys, "frozen", False):
            command += ["-m", "lalc"]
        command += ["--candidate-runner", str(request_path)]
        self._runner = subprocess.Popen(command, text=True)
        self._phase("candidate_trial")
        try:
            return_code = self._runner.wait(timeout=self.runner_timeout)
        except subprocess.TimeoutExpired:
            self._runner.kill()
            self._runner.wait()
            return {"status": "failure", "failure_code": "candidate_timeout"}
        finally:
            self._runner = None
        if not result_path.exists():
            return {"status": "failure", "failure_code": "candidate_result_missing", "exit_code": return_code}
        result = json.loads(result_path.read_text(encoding="utf-8"))
        if return_code != 0 or result.get("status") != "success":
            return {"status": "failure", "failure_code": result.get("failure_code", "candidate_process_failed")}
        return result

    def _show_runtime_review(self, candidate: dict[str, Any]) -> None:
        self._runtime_decision = None
        self._set_state(
            phase="runtime_review",
            pending_review={
                "source": candidate["source"],
                "sha256": candidate["sha256"],
                "manifest": candidate["manifest"],
                "warning": "候选 Python 不是安全沙箱，可能访问文件、网络、进程和系统 API。",
            },
        )

    def _wait_runtime_decision(self) -> tuple[str, str]:
        with self._condition:
            self._condition.wait_for(lambda: self._runtime_decision is not None or self.gate.stopped)
            if self._runtime_decision is None:
                return "terminate", ""
            decision = self._runtime_decision
            self._runtime_decision = None
            if decision[0] == "reject":
                self._state["last_feedback"] = decision[1]
            return decision

    def _finish(self, result: dict[str, Any], candidate: dict[str, Any] | None, trial_succeeded: bool) -> None:
        if candidate:
            selected_candidate = (
                self._working_manifest["components"]["example.current_step"].get("sha256") == candidate["sha256"]
            )
            proposal = {
                "manifest": deepcopy(self._working_manifest if selected_candidate else candidate["manifest"]),
                "source_path": candidate["source_path"],
                "source": candidate["source"],
                "structural_validation": "passed",
                "trial_succeeded": trial_succeeded,
                "validation_coverage": ["candidate_step"] if trial_succeeded else [],
                "result": result,
                "trace": deepcopy(self._state["trace"]),
            }
            assert self._run_dir is not None
            atomic_write_json(self._run_dir / "capability-proposal.json", proposal)
            self._capability_decision = None
            self._set_state(phase="capability_review", result=result, pending_review=None, pending_capability=proposal)
            with self._condition:
                self._condition.wait_for(lambda: self._capability_decision is not None)
                decision = self._capability_decision
            self._trace("capability_reviewed", decision=decision, trial_succeeded=trial_succeeded)
            if decision == "approve":
                approved = deepcopy(proposal["manifest"])
                approved["manifest_id"] = f"approved-{uuid.uuid4().hex[:12]}"
                atomic_write_json(self.data_root / "manifests" / f"{approved['manifest_id']}.json", approved)
                atomic_write_json(self.data_root / "manifests" / "active.json", approved)
                self._active_manifest = approved
                self._set_state(active_manifest_id=approved["manifest_id"])
        self._phase("finished", result=result, pending_review=None, pending_capability=None)

    def _replace_working_manifest(self, manifest: dict[str, Any]) -> None:
        assert self._run_dir is not None
        replacement = deepcopy(manifest)
        atomic_write_json(self._run_dir / "working-manifest.json", replacement)
        self._working_manifest = replacement
        self._set_state(working_manifest_id=replacement["manifest_id"])

    def _trace(self, event: str, **fields: Any) -> None:
        record = {"sequence": len(self._state["trace"]) + 1, "event": event, **fields}
        with self._condition:
            self._state["trace"].append(record)
            assert self._run_dir is not None
            trace_path = self.data_root / "traces" / f"{self._run_dir.name}.jsonl"
            with trace_path.open("a", encoding="utf-8") as stream:
                stream.write(json.dumps(record, ensure_ascii=False) + "\n")
            self._changed_locked()

    def _phase(self, phase: str, **fields: Any) -> None:
        self._set_state(phase=phase, **fields)

    def _set_state(self, **fields: Any) -> None:
        with self._condition:
            self._state.update(fields)
            self._changed_locked()

    def _changed_locked(self) -> None:
        self._condition.notify_all()
        callback = self.on_change
        snapshot = deepcopy(self._state)
        if callback:
            callback(snapshot)


def default_data_root() -> Path:
    if sys.platform == "win32":
        import os

        return Path(os.environ.get("LOCALAPPDATA", Path.home())) / "LALC"
    return Path.home() / ".local" / "share" / "LALC"
